def options(opt):
    opt.load("compiler_cxx")
    opt.recurse("python")
    opt.recurse("tests")

def configure(conf):
    conf.recurse("python")
    conf.recurse("tests")
    base_env = conf.env.derive()

    conf.setenv("debug", base_env)
    conf.load("compiler_cxx")
    conf.env.CXXFLAGS = ["-g", "-ggdb"]

    conf.setenv("release", base_env)
    conf.load("compiler_cxx")
    conf.env.CXXFLAGS = ["-O2"]

def build(bld):
    bld(
        target="snn",
        features="cxx cxxshlib",
        source=[
            "source/connections.cpp",
            "source/group.cpp",
            "source/network.cpp",
        ],
        includes=[
            bld.path.find_dir("include"),
        ],
        export_includes=[
            bld.path.find_dir("include"),
        ],
        cxxflags=[
            "-std=c++11",
        ],
    )
    bld.recurse("python")
    bld.recurse("tests")

from waflib.Build import BuildContext
class debug(BuildContext):
    cmd = "debug"
    variant = "debug"

class release(BuildContext):
    cmd = "release"
    variant = "release"
