def options(opt):
    opt.load("compiler_cxx")
    opt.load("boost")

def configure(conf):
    conf.load("compiler_cxx")

    conf.load("python")
    conf.check_python_headers()

    conf.load("boost")
    conf.check_boost("python")

def build(bld):
    bld(
        target="snn",
        features="cxx cxxshlib pyext",
        source=[
            "source/network.cpp",
            "source/python/module.cpp",
            "source/python/network.cpp",
            "source/python/numpy_initializer.cpp",
        ],
        includes=[
            bld.path.find_dir("include"),
        ],
        lib=[
            "boost_numpy",
        ],
        use=[
            "BOOST",
        ],
    )
