def options(opt):
    opt.load("compiler_cxx")

def configure(conf):
    conf.load("compiler_cxx")

def build(bld):
    bld(
        target="snn-tests",
        features="cxx cxxprogram",
        source=[
            "main.cpp",
            "snn.cpp"
        ],
        lib=[
            "gtest",
        ],
        cxxflags=[
            "-std=c++11",
        ],
        use=[
            "snn"
        ],
    )
